#!/usr/bin/env python3
"""Generate src/bundle_gen.h: the changes of the three earlier mods (Combo Flow, KH2 Camera, Revenge Value)
in the form the DLL applies in memory.

Inputs:
  BBS_EXE            unmodified game exe
  BBS_EXE_COMBO      the same exe with the Combo Flow patch installed (only the differing code bytes are kept)
  bundle_src/patches.json        byte changes of PAtkData.bin and the camera files against the originals
  bundle_src/Factory_revenge.lub the Revenge Value build of Factory.lub (Lua 5.1 bytecode)
"""
import json, os, struct, sys, zlib
R=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(R,'tools'))
from bbsexe import PE
a=PE(os.environ['BBS_EXE']); b=PE(os.environ['BBS_EXE_COMBO'])
da,db=bytes(a.d),bytes(b.d)
def rva(off):
    for n,va,vs,ro,rs in a.secs:
        if ro<=off<ro+rs: return va+off-ro
    return None
diff=[i for i in range(len(da)) if da[i]!=db[i] and rva(i) is not None]
runs=[]; s=p=diff[0]
for i in diff[1:]:
    if i-p>8: runs.append((s,p+1)); s=i
    p=i
runs.append((s,p+1))
out=['/* generated by tools/genbundle.py */']
def carr(name,data):
    out.append('static const u8 %s[] = {%s};'%(name,','.join('0x%02x'%x for x in data)))
out.append('/* ---- Combo Flow: code changes (rva, length, original bytes, new bytes) ---- */')
for k,(i,j) in enumerate(runs):
    carr('cf_old%d'%k,da[i:j]); carr('cf_new%d'%k,db[i:j])
out.append('static const struct { u32 rva; u32 len; const u8 *old, *neu; } cf_code[] = {')
for k,(i,j) in enumerate(runs): out.append('    { 0x%x, %d, cf_old%d, cf_new%d },'%(rva(i),j-i,k,k))
out.append('};')
P=json.load(open(os.path.join(R,'bundle_src','patches.json')))
out.append('/* ---- data files patched in place when the game loads them: (offset, value) pairs ---- */')
seen={}
for f in P['files']:
    key=(f['inner'],f['size'],f['crc_vanilla'],f['crc_new'])
    if key in seen: continue
    seen[key]=(f['mod'],f['diffs'])
for k,(key,(mod,diffs)) in enumerate(seen.items()):
    out.append('static const u16 df_set%d[] = {%s};'%(k,','.join('%d,%d'%(o,v) for o,v in diffs)))
out.append('static const struct { const char *name; u32 size, crc_old, crc_new; u8 group; u16 n; const u16 *set; } df_files[] = {')
for k,(key,(mod,diffs)) in enumerate(seen.items()):
    grp=0 if mod=='BBS-Combo-Flow' else 1
    out.append('    { "%s", %d, 0x%08x, 0x%08x, %d, %d, df_set%d },'%(key[0],key[1],key[2],key[3],grp,len(diffs),k))
out.append('};')
lub=open(os.path.join(R,'bundle_src','Factory_revenge.lub'),'rb').read()
out.append('/* ---- Revenge Value: Factory.lub (replaces the 638-byte original, crc 0x%08x) ---- */'%0)
carr('rv_factory',lub)
open(os.path.join(R,'src','bundle_gen.h'),'w').write('\n'.join(out)+'\n')
print('code runs:',[(hex(rva(i)),j-i) for i,j in runs],'data files:',len(seen),'lub',len(lub))
