#!/usr/bin/env python3
"""genhdart.py -> src/hdart_gen.h

Builds the words MAGIC, ITEMS and D-LINK for the headers of the command menu's lists (drawn by tools/hdfont.py, in
the style of the game's "COMMANDS" label; nothing is copied from the game), and the check pixels by which the
game's command sheet - the texture of bc01_00.l2d, 1024 x 1024 - is recognised when it is loaded.

Inputs: the remastered command sheets of your own game files, one per language you have at hand, as
    CMD_SHEET_PNGS="en.png:jp.png:fr.png"
(texture 5 of arc_en/pc/p00common.arc and of arc/pc/p00common.arc, texture 0 of arc_fr/pc/p00common.arc).  The check
pixels are taken where all of them agree, and the art goes to an area all of them leave empty.
"""
import os, sys
import numpy as np
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hdfont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sheets = [np.array(Image.open(p).convert('RGBA')) for p in os.environ['CMD_SHEET_PNGS'].split(':')]
assert all(s.shape == (1024, 1024, 4) for s in sheets)

# the words, stacked: each in a cell 40 pixels high (20 texture units, as the game's label), 4 clear rows between
OX, OY = 16, 740                 # where the block goes in the sheet (pixels, even)
CELL, STEP = 40, 44
words = {}
ims = []
for i, t in enumerate(('MAGIC', 'ITEMS', 'D-LINK')):
    im, x0, y0 = hdfont.word(t, pad=(4, 4, 8, 12))
    assert im.shape[0] == CELL, im.shape
    if im.shape[1] % 4: im = np.concatenate([im, np.zeros((CELL, 4 - im.shape[1] % 4, 4), np.float32)], 1)
    ims.append(im); words[t] = (0, i * STEP, im.shape[1], CELL)
PW = max(im.shape[1] for im in ims) + 4; PW += -PW % 4
PH = STEP * len(ims)
patch = np.zeros((PH, PW, 4), np.float32)
for im, (x, y, w, h) in zip(ims, words.values()): patch[y:y + h, x:x + w] = im
patch[patch[:, :, 3] < 0.5, :3] = 0
p8 = np.clip(patch + 0.5, 0, 255).astype(np.uint8)
for s in sheets:
    assert s[OY - 4:OY + PH + 4, OX - 4:OX + PW + 4, 3].max() == 0, 'target area of a command sheet is not empty'

# check pixels: opaque, flat surroundings, the same in every sheet given
rng = np.random.RandomState(11)
s16 = [s.astype(np.int16) for s in sheets]
same = np.ones((1024, 1024), bool)
for s in s16[1:]: same &= np.abs(s - s16[0]).max(axis=2) <= 2
flat_ok = np.ones((1024, 1024), bool)
def pick(mask, count, tol):
    out = []
    ys, xs = np.nonzero(mask)
    for i in rng.permutation(len(ys)):
        y, x = int(ys[i]), int(xs[i])
        if not (2 <= y < 1022 and 2 <= x < 1022): continue
        if not same[y - 2:y + 3, x - 2:x + 3].all(): continue
        blk = s16[0][y - 2:y + 3, x - 2:x + 3].reshape(-1, 4)
        if np.abs(blk - blk[12]).max() > tol: continue
        if any(abs(x - cx) + abs(y - cy) < 40 for cx, cy, *_ in out): continue
        out.append((x, y) + tuple(int(v) for v in sheets[0][y, x]))
        if len(out) == count: break
    assert len(out) == count, len(out)
    return out
opaque = sheets[0][:, :, 3] == 255
checks = pick(opaque, 24, 3)        # the art is grey, so the byte order of the pixels does not matter here

with open(os.path.join(ROOT, 'src', 'hdart_gen.h'), 'w') as f:
    f.write('/* generated by tools/genhdart.py - do not edit */\n')
    f.write('#define HDART_SHEET 1024\n#define HDART_W %d\n#define HDART_H %d\n#define HDART_X %d\n#define HDART_Y %d\n' % (PW, PH, OX, OY))
    f.write('/* the words: texture rectangle in units of the 512 x 512 sheet (u, v, width, height) */\n')
    for name, (x, y, w, h) in words.items():
        n = name.replace('-', '')
        f.write('#define HDART_%s_U %d\n#define HDART_%s_V %d\n#define HDART_%s_W %d\n#define HDART_%s_H %d\n' % (n, (OX + x) // 2, n, (OY + y) // 2, n, w // 2, n, h // 2))
    f.write('#ifdef HDART_DATA\n')
    f.write('static const struct { unsigned short x, y; unsigned char r, g, b, a; } hdart_checks[%d] = {\n' % len(checks))
    for c in checks: f.write('    { %d, %d, %d, %d, %d, %d },\n' % c)
    f.write('};\n')
    flat = p8.reshape(-1, 4)
    assert (flat[:, 0] == flat[:, 1]).all() and (flat[:, 0] == flat[:, 2]).all()
    runs = []
    i = 0
    while i < len(flat):
        j = i
        while j < len(flat) and j - i < 255 and (flat[j] == flat[i]).all(): j += 1
        runs.append((j - i, int(flat[i][0]), int(flat[i][3]))); i = j
    f.write('/* run-length coded rows: (count, grey, alpha) */\n')
    f.write('static const unsigned char hdart_rle[%d] = {\n' % (len(runs) * 3))
    for k in range(0, len(runs), 10):
        f.write('    ' + ' '.join('%d,%d,%d,' % r for r in runs[k:k + 10]) + '\n')
    f.write('};\n#endif\n')
print('patch %dx%d px at (%d,%d), %d runs (%d bytes), %d check pixels' % (PW, PH, OX, OY, len(runs), len(runs) * 3, len(checks)), words)
if len(sys.argv) > 1:
    out = sheets[0].copy(); out[OY:OY + PH, OX:OX + PW] = p8
    Image.fromarray(out).save(sys.argv[1])
