#!/usr/bin/env python3
"""genproxy.py NAME -> src/proxy_gen.S and out/NAME.def: forwarding stubs for every export of the system
DLL called NAME (dinput8 or dbghelp), so that the mod can sit next to the game exe under that name.
The name must be a DLL the game imports that is NOT one of Windows' "known DLLs" (those are always taken from
System32: imagehlp, shlwapi, setupapi ... cannot be used)."""
import os, sys
R=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
name=sys.argv[1] if len(sys.argv)>1 else 'dinput8'
names=sorted({l.strip() for fn in (name+'_exports.txt',name+'_exports_extra.txt') for l in open(os.path.join(R,'tools',fn)) if l.strip()})
s=['/* generated by genproxy.py %s */'%name,'    .intel_syntax noprefix','    .text','    .globl proxy_resolve']
for i,n in enumerate(names):
    s+=['    .globl px_%s'%n,'px_%s:'%n,'    jmp qword ptr [rip + proxy_table + %d]'%(i*8),
        'lazy_%d:'%i,'    mov r11d, %d'%i,'    jmp lazy_common']
s+=['lazy_common:','    push rcx','    push rdx','    push r8','    push r9','    sub rsp, 0x28',
    '    mov ecx, r11d','    call proxy_resolve','    add rsp, 0x28','    pop r9','    pop r8','    pop rdx','    pop rcx','    jmp rax',
    '    .globl proxy_fail','proxy_fail:','    xor eax, eax','    ret',
    '    .data','    .globl proxy_table','    .balign 8','proxy_table:']
s+=['    .quad lazy_%d'%i for i in range(len(names))]
s+=['    .section .rdata,"dr"','    .globl proxy_names','    .balign 8','proxy_names:']
s+=['    .quad pn_%d'%i for i in range(len(names))]
s+=['pn_%d: .asciz "%s"'%(i,n) for i,n in enumerate(names)]
s+=['    .globl proxy_count','    .balign 4','proxy_count: .long %d'%len(names),
    '    .globl proxy_dll','proxy_dll: .asciz "\\\\%s.dll"'%name]
open(os.path.join(R,'src','proxy_gen.S'),'w').write('\n'.join(s)+'\n')
os.makedirs(os.path.join(R,'out'),exist_ok=True)
open(os.path.join(R,'out',name+'.def'),'w').write('LIBRARY %s\nEXPORTS\n'%name+''.join('  %s = px_%s%s\n'%(n,n,' PRIVATE' if n.startswith('Dll') else '') for n in names))
print(name,len(names),'exports')
