#!/usr/bin/env python3
"""genstatart.py -> src/statart_gen.h

The "MP" label for the character panel of the menu.  The panel's labels (LV, HP, FP, NEXT LEVEL) are small
pixel-font glyphs in the menu's texture sheet (remastered texture of camp.l2d, 1024x1024): letters 10 texels
high with strokes 2 wide, grey, tinted by the game.  There is no "M" among them, so one is drawn here in the
same style; the "P" is copied from the sheet's own "HP" when the game loads the texture (src/tex.c).

Input (your own game files): BBS_CAMP_PNG = that texture (arc_en/menu/camp.arc, "US_camp_arc6.png").
It is only used to compute the check value by which the sheet is recognised at run time.
"""
import os
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SS = 8
def glyph_m(w=10, h=10):
    """two stems and a V between them, anti-aliased like the sheet's own N and V"""
    out = np.zeros((h, w))
    for py in range(h):
        for px in range(w):
            c = 0
            for sy in range(SS):
                for sx in range(SS):
                    x = px + (sx + .5) / SS; y = py + (sy + .5) / SS
                    cl = 1.75 + 0.62 * y; cr = w - cl
                    c += x < 2 or x >= w - 2 or (y < 5.9 and (abs(x - cl) < 0.98 or abs(x - cr) < 0.98))
            out[py, px] = c / SS / SS
    return np.clip(out * 255 + .5, 0, 255).astype(np.uint8)

# where things are in the sheet (texels)
HP = (34, 646, 58, 662)          # the "HP" label's cell; H at x 36..43, P at x 46..53, rows 648..657
FP = (62, 646, 86, 662)
P_SRC = (46, 648, 8, 10)         # the P of "HP": x, y, w, h
CELL = (300, 676, 26, 16)        # the new "MP" cell: an area no sprite uses and that is empty in every variant
M_AT = (2, 2); P_AT = (14, 2)    # inside the cell

def fnv(bits):
    h = 0x811c9dc5
    for b in bits:
        h = ((h ^ int(b)) * 0x01000193) & 0xffffffff
    return h

a = np.array(Image.open(os.environ['BBS_CAMP_PNG']).convert('RGBA'))
assert a.shape == (1024, 1024, 4)
region = a[HP[1]:HP[3], HP[0]:FP[2], 3] >= 128
check = fnv(region.reshape(-1))
assert a[CELL[1] - 4:CELL[1] + CELL[3] + 4, CELL[0] - 4:CELL[0] + CELL[2] + 4, 3].max() == 0, 'target area is in use'
m = glyph_m()
o = ['/* generated by tools/genstatart.py */',
     '#define STAT_SHEET 1024',
     '#define STAT_CHK_X %d\n#define STAT_CHK_Y %d\n#define STAT_CHK_W %d\n#define STAT_CHK_H %d' % (HP[0], HP[1], FP[2] - HP[0], HP[3] - HP[1]),
     '#define STAT_CHK 0x%08xu          /* FNV-1a over (alpha >= 128) of that area, row by row */' % check,
     '#define STAT_P_X %d\n#define STAT_P_Y %d\n#define STAT_P_W %d\n#define STAT_P_H %d' % P_SRC,
     '#define STAT_CELL_X %d\n#define STAT_CELL_Y %d\n#define STAT_CELL_W %d\n#define STAT_CELL_H %d' % CELL,
     '#define STAT_M_X %d\n#define STAT_M_Y %d\n#define STAT_M_W 10\n#define STAT_M_H 10' % M_AT,
     '#define STAT_PD_X %d\n#define STAT_PD_Y %d' % P_AT,
     '#ifdef STATART_DATA', 'static const unsigned char stat_m[STAT_M_H][STAT_M_W] = {']
for r in m: o.append('    {' + ','.join('%3d' % v for v in r) + '},')
o += ['};', '#endif']
open(os.path.join(ROOT, 'src', 'statart_gen.h'), 'w').write('\n'.join(o) + '\n')
print('check %08x' % check)
