#!/usr/bin/env python3
"""Generate src/steals_gen.h: the bytes each hook overwrites (needs the unmodified game exe, BBS_EXE)."""
import os
from bbsexe import ROOT
from steal import steal,raw
S=[ # (name, rva, minlen)  relocatable steals (function entries)
 ('S_gauge_init',0x209070,5),('S_gauge_update',0x209f20,5),('S_gauge_dtor',0x2080a0,5),
 ('S_dlink_open',0x2388a0,5),('S_dlink_pick',0x205ee0,5),
 ('S_item_effect',0x2624e0,5),('S_pd_init',0x285780,5),
 ('S_deck_input',0x233a00,5),('S_confirm',0x272860,5),
 ('S_style_decide',0x2368f2,5),
 # style.c: the start of a style change (28a950) asks "in the air?" (264a10) before choosing to fall first
 ('S_style_air',0x28ac22,5),
 # speed.c: the "has this action ended?" tests of the action states, and the fall-loop hover test
 ('S_atk_end',0x2291bf,8),('S_mag_anim',0x26825f,5),('S_mag_lock',0x26828a,8),
 ('S_deck_a',0x2246c0,8),('S_deck_b',0x224476,8),('S_deck_c',0x2253ff,8),
 ('S_item_end',0x262056,8),('S_friend_end',0x2599ab,8),('S_fin_end',0x2562bc,8),
 ('S_fall_hover',0x2633ff,6),
 # speed.c: the combo table's conditions are built (2239b0): "target above" for the launcher
 ('S_launch',0x223b0d,5),
 # status.c: Destroy(instance handle) of the 2D-layout runtime
 ('S_l2d_destroy',0x1a57f0,5),
]
R=[('S_gravity',0x21cb55,5)]   # never executed: the handler always redirects
out=['/* generated by gensteal.py */']
for n,a,m in S: out.append(steal(n,a,m))
for n,a,m in R: out.append(raw(n,a,m))
open(os.path.join(ROOT,'src','steals_gen.h'),'w').write('\n'.join(out)+'\n')
print('%d hook sites written to src/steals_gen.h'%(len(S)+len(R)))
