/* generated by tools/genstatart.py */
#define STAT_SHEET 1024
#define STAT_CHK_X 34
#define STAT_CHK_Y 646
#define STAT_CHK_W 52
#define STAT_CHK_H 16
#define STAT_CHK 0x5bc8189au          /* FNV-1a over (alpha >= 128) of that area, row by row */
#define STAT_P_X 46
#define STAT_P_Y 648
#define STAT_P_W 8
#define STAT_P_H 10
#define STAT_CELL_X 300
#define STAT_CELL_Y 676
#define STAT_CELL_W 26
#define STAT_CELL_H 16
#define STAT_M_X 2
#define STAT_M_Y 2
#define STAT_M_W 10
#define STAT_M_H 10
#define STAT_PD_X 14
#define STAT_PD_Y 2
#ifdef STATART_DATA
static const unsigned char stat_m[STAT_M_H][STAT_M_W] = {
    {255,255,239, 24,  0,  0, 24,239,255,255},
    {255,255,255,167,  0,  0,167,255,255,255},
    {255,255,175,255, 72, 72,255,175,255,255},
    {255,255, 28,243,223,223,243, 28,255,255},
    {255,255,  0,112,255,255,112,  0,255,255},
    {255,255,  0, 32,223,223, 32,  0,255,255},
    {255,255,  0,  0,  0,  0,  0,  0,255,255},
    {255,255,  0,  0,  0,  0,  0,  0,255,255},
    {255,255,  0,  0,  0,  0,  0,  0,255,255},
    {255,255,  0,  0,  0,  0,  0,  0,255,255},
};
#endif
